### ISSUE TITLE
First version checklist

### ISSUE THREAD

**Issue by tumb1er** [tumb1er/aioworkerpool#1]
- [x] start a number of workers
- [x] restart exited workers
- [x] check for worker freeze and restart it
- [x] daemonize
- [x] multiprocessing logging
- [x] preserve sockets and open files
- [x] documentation
- [x] tests
- [x] real-world project integration
- [x] upload to pypi
